### ISSUE TITLE
Relative config path confusion and panic

### ISSUE THREAD

**Issue by mpenning** [mpenning/ssh_logger#2]
We hit a panic here...

```
$ ./ssh_logger --yaml ~/.ssh_logger/configs/route_views.yaml
2023-11-10 06:25:16.510 | CRITICAL | Config File "/home/mpenning/.ssh_logger/configs/route_views.yaml" Not Found in "[/home/mpenning/fixme/ssh_logger /home/mpenning/.ssh_logger/configs]"
panic: 2023-11-10 06:25:16.510 | CRITICAL | Config File "/home/mpenning/.ssh_logger/configs/route_views.yaml" Not Found in "[/home/mpenning/fixme/ssh_logger /home/mpenning/.ssh_logger/configs]"


goroutine 1 [running]:
log.Panicln({0xc00011dc20?, 0xdf?, 0x1?})
        /home/mpenning/go/src/log/log.go:398 +0x65
github.com/gleich/logoru.Critical({0xc00011de48, 0x1, 0x1})
        /home/mpenning/go/bin:[0]/pkg/mod/github.com/gleich/logoru@v0.0.0-20230101033757-d86cd895c7a1/levels.go:52 +0xc9
main.main()
        /home/mpenning/fixme/ssh_logger/main.go:120 +0x61e

```

**Comment by mpenning** [comment]
This was fixed in [ssh_logger PR #1](https://github.com/mpenning/ssh_logger/pull/1)
